### ISSUE TITLE
problem with quest and original files

### ISSUE THREAD

**Issue by ezemania2** [Malckyor/MHF-Z-Personal-Adjustments-W.I.P#3]
we have a bug when we want to play with original files, the key quest their automaticly clear and we can't do the urgent quest

**Comment by Malckyor** [comment]
I saw a few people having this issue and then I added a note in the readme for that, it might happens that the progression is saved to your character to keep track of which quests you have cleared for it to trigger the urgent quest, I don't think that I have the skills to fix that (I might even have if it's stored in the savedata) but I've made this with no intention to change back to the vanilla version.
I'm sorry to say that but either you keep playing with it until you reach GR or start with a new character without this patch.

**Comment by rnrjsghl12** [comment]
![unknown](https://user-images.githubusercontent.com/77409740/161018682-b3a7dbe0-1cc7-41af-ad22-871925145dfa.png)
How do you activate it?

**Comment by Malckyor** [comment]
I don't know, after the Z updates I didn't do any more events and since it was guild related I left my guild in G9 and never joined other, I don't know how these events works.

**Comment by VictorChan7** [comment]
《you'll have to clear the key quests again to reset the key quest counter and unlock the urgent quest,》Hello, how to clear?

**Comment by Malckyor** [comment]
Sorry for the late reply, use Chakratos save manager to do that, he made that function for this reason.

https://github.com/Chakratos/mhf-save-manager/releases
